[project]
name = "Telight-python"
description = "Telight AI Python env"
authors = ["Vladimír Ulman <vladimir.ulman@vsb.cz>"]
repository = "https://github.com/xulman/Telight-SD3"

license = "BSD-2-Clause"
#license-file = "LICENSE"
readme = "README.md"

platforms = ["linux-64"]
channels = ["conda-forge", "pytorch"]
version = "0.1.0"

[system-requirements]

[tasks]

[dependencies]
pytorch = "==2.4.1"
torchvision = "~=0.19.0"
scikit-image = ">=0.24.0,<0.25"
scikit-learn = ">=1.5.2,<2"
tifffile = ">=2024.6.18,<2025"
imagecodecs = ">=2024.9.22,<2025"
tqdm = ">=4.67.1,<5"
pandas = ">=2.2.3,<3"
albumentations = ">=1.4.20,<2"
pybind11 = ">=2.13.6,<3"

